frontend_controllers:
    resource: ../../Controller/Frontend
    type: attribute
    prefix: /account
    name_prefix: account.
api_controllers:
    resource: ../../Controller/Api
    type: attribute
    prefix: /api/account
    name_prefix: api_account.