doctrine:
    dbal:
        connections:
            account:
                url: '%env(resolve:ACCOUNT_DATABASE)%'
                driver: 'pdo_sqlsrv'
                charset: UTF-8
                server_version: '2019'
            character:
                url: '%env(resolve:CHARACTER_DATABASE)%'
                driver: 'pdo_sqlsrv'
                charset: UTF-8
                server_version: '2019'
            website:
                url: '%env(resolve:WEBSITE_DATABASE)%'
                driver: 'pdo_sqlsrv'
                charset: UTF-8
                server_version: '2019'
        default_connection: account
    orm:
        controller_resolver:
            auto_mapping: true
        default_entity_manager: account
        entity_managers:
            account:
                connection: account
                mappings:
                    Account:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Bundles/AccountBundle/Entity'
                        prefix: 'App\Bundles\AccountBundle\Entity'
                        alias: Account
            character:
                connection: character
                mappings:
                    Character:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Bundles/CharacterBundle/Entity'
                        prefix: 'App\Bundles\CharacterBundle\Entity'
                        alias: Character
            website:
                connection: website
                mappings:
                    Website:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Bundles/MainBundle/Entity'
                        prefix: 'App\Bundles\MainBundle\Entity'
                        alias: Website
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
