services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundles\ShopBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    App\Bundles\ShopBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
