services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundles\CharacterBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'
